framework:
 cache:
  pools:
   ergonode_gql_request_cache:
    adapter: cache.adapter.filesystem
    default_lifetime: -1
   ergonode_attribute_mapping_cache:
    adapter: cache.adapter.filesystem
    default_lifetime: 300