monolog:
 channels: [ ergonodeApi, ergonodeSync ]
 handlers:
  ergonodeApi:
   type: rotating_file
   path: "%kernel.logs_dir%/ergonode_integration/api.%kernel.environment%.log"
   level: debug
   max_files: 14
   formatter: 'monolog.formatter.json'
   channels: [ ergonodeApi ]
  ergonodeSync:
   type: rotating_file
   path: "%kernel.logs_dir%/ergonode_integration/sync.%kernel.environment%.log"
   level: debug
   max_files: 14
   formatter: 'monolog.formatter.json'
   channels: [ ergonodeSync ]