monolog:
 channels: [ sync_logger ]
 handlers:
  sync_logger:
   type: rotating_file
   path: "%kernel.logs_dir%/sync.%kernel.environment%.log"
   level: debug
   max_files: 10
   channels: [ sync_logger ]