imports:
  - { resource: packages/cache.yml }
services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    # TRANSFORMER
    Strix\Ergonode\Transformer\NodeTransformerInterface:
      tags: [ 'strix_ergonode.node_transformer' ]
      lazy: true

  # WIRE WHOLE NAMESPACE
  Strix\Ergonode\:
    resource: '../../'

  # API
  Strix\Ergonode\Api\Client\ErgonodeGqlClient:
    factory: [ '@Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory', 'createFromPluginConfig' ]

  Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory:

  # RESOLVER
  Strix\Ergonode\Resolver\NodeTransformerResolver:
    arguments:
      - !tagged_iterator { tag: 'strix_ergonode.node_transformer' }

  # SUBSCRIBER
  Strix\Ergonode\Subscriber\Subscriber:
    tags: [ 'kernel.event_subscriber' ]