imports:
  - { resource: parameters.yml }
  - { resource: packages/cache.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    # EXTENSION
    Strix\Ergonode\Extension\AbstractErgonodeMappingExtension:
      tags: [ 'shopware.entity.extension' ]

    # TRANSFORMER
    Strix\Ergonode\Transformer\CustomField\CustomFieldTransformerInterface:
      tags: ['strix_ergonode.custom_field_transformer']

  # WIRE WHOLE NAMESPACE
  Strix\Ergonode\:
    resource: '../../'

  # API
  Strix\Ergonode\Api\Client\ErgonodeGqlClient:
    factory: [ '@Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory', 'createFromPluginConfig' ]

  Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory:

  # CONTROLLER
  Strix\Ergonode\Modules\Attribute\Controller\AttributeMappingController:
    tags: [ 'controller.service_arguments' ]

  # COMMAND
  Strix\Ergonode\Modules\Attribute\Command\CreateAttributeMappingCommand:
    arguments:
      $repository: '@strix_ergonode_attribute_mapping.repository'

  # ENTITY DEFINITION
  Strix\Ergonode\Modules\Attribute\Entity\ErgonodeAttributeMapping\ErgonodeAttributeMappingDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeMappingExtension\ErgonodeMappingExtensionEntityDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeCategoryMappingExtensionEntityDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeCursor\ErgonodeCursorDefinition:
    tags: [ 'shopware.entity.definition' ]

  # EXTENSION
  Strix\Ergonode\Extension\ErgonodeCategoryMappingExtension:
    tags: [ 'shopware.entity.extension' ]

  # MANAGER
  Strix\Ergonode\Manager\ErgonodeCursorManager:
    arguments:
      $repository: '@strix_ergonode_cursor.repository'

  # PROVIDER
  Strix\Ergonode\Modules\Attribute\Provider\AttributeMappingProvider:
    arguments:
      $repository: '@strix_ergonode_attribute_mapping.repository'

  # RESOLVER
  Strix\Ergonode\Resolver\CustomFieldTransformerResolver:
    arguments:
      - !tagged_iterator { tag: 'strix_ergonode.custom_field_transformer' }

  # SUBSCRIBER
  Strix\Ergonode\Subscriber\Subscriber:
    tags: [ 'kernel.event_subscriber' ]

  # TRANSFORMER
  Strix\Ergonode\Transformer\ProductTransformerChain:
    arguments:
      $transformers:
        - '@Strix\Ergonode\Transformer\ProductTransformer'
        - '@Strix\Ergonode\Transformer\ProductTaxTransformer'
        - '@Strix\Ergonode\Transformer\ProductPriceTransformer'