imports:
  - { resource: parameters.yml }
  - { resource: packages/cache.yml }
  - { resource: packages/monolog.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    # EXTENSION
    Strix\Ergonode\Extension\AbstractErgonodeMappingExtension:
      tags: [ 'shopware.entity.extension' ]

    # TRANSFORMER
    Strix\Ergonode\Transformer\CustomField\CustomFieldTransformerInterface:
      tags: ['strix_ergonode.custom_field_transformer']

    Strix\Ergonode\Transformer\ProductCustomField\ProductCustomFieldTransformerInterface:
      tags: [ 'strix_ergonode.product_custom_field_transformer' ]

  # WIRE WHOLE NAMESPACE
  Strix\Ergonode\:
    resource: '../../'

  # API
  Strix\Ergonode\Api\Client\ErgonodeGqlClient:
    factory: [ '@Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory', 'createFromPluginConfig' ]

  Strix\Ergonode\Api\Client\ErgonodeGqlClientFactory:

  # CONTROLLER
  Strix\Ergonode\Controller\AttributeMappingController:
    tags: [ 'controller.service_arguments' ]

  # COMMAND
  Strix\Ergonode\Command\CreateAttributeMappingCommand:
    arguments:
      $repository: '@strix_ergonode_attribute_mapping.repository'

  # ENTITY DEFINITION
  Strix\Ergonode\Entity\ErgonodeAttributeMapping\ErgonodeAttributeMappingDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeMappingExtension\ErgonodeMappingExtensionDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeCategoryMappingExtension\ErgonodeCategoryMappingExtensionDefinition:
    tags: [ 'shopware.entity.definition' ]

  Strix\Ergonode\Entity\ErgonodeCursor\ErgonodeCursorDefinition:
    tags: [ 'shopware.entity.definition' ]

  # EXTENSION
  Strix\Ergonode\Extension\ErgonodeCategoryMappingExtension:
    tags: [ 'shopware.entity.extension' ]

  # LOCK
  strix.ergonode.flock-store:
    class: Symfony\Component\Lock\Store\FlockStore

  strix.ergonode.lock-factory:
    class: Symfony\Component\Lock\LockFactory
    arguments:
      - '@strix.ergonode.flock-store'
    calls:
      - setLogger: [ '@monolog.logger.sync' ]

  # MANAGER
  Strix\Ergonode\Manager\ErgonodeCursorManager:
    arguments:
      $repository: '@strix_ergonode_cursor.repository'

  # PROVIDER
  Strix\Ergonode\Provider\AttributeMappingProvider:
    arguments:
      $repository: '@strix_ergonode_attribute_mapping.repository'

  # RESOLVER
  Strix\Ergonode\Resolver\CustomFieldTransformerResolver:
    arguments:
      - !tagged_iterator { tag: 'strix_ergonode.custom_field_transformer' }

  Strix\Ergonode\Resolver\ProductCustomFieldTransformerResolver:
    arguments:
      - !tagged_iterator { tag: 'strix_ergonode.product_custom_field_transformer' }

  # SCHEDULED TASK
  Strix\Ergonode\Service\ScheduledTask\ProductSyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\ProductVisibilitySyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\CategorySyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\AttributeSyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\LanguageSyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\CategoryTreeSyncTask:
    tags: [ 'shopware.scheduled.task' ]

  Strix\Ergonode\Service\ScheduledTask\ProductSyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  Strix\Ergonode\Service\ScheduledTask\ProductVisibilitySyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  Strix\Ergonode\Service\ScheduledTask\CategorySyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  Strix\Ergonode\Service\ScheduledTask\AttributeSyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  Strix\Ergonode\Service\ScheduledTask\LanguageSyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  Strix\Ergonode\Service\ScheduledTask\CategoryTreeSyncTaskHandler:
    tags: [ 'messenger.message_handler' ]
    arguments:
      $lockFactory: '@strix.ergonode.lock-factory'

  # SUBSCRIBER
  Strix\Ergonode\Subscriber\Subscriber:
    tags: [ 'kernel.event_subscriber' ]

  # TRANSFORMER
  Strix\Ergonode\Transformer\ProductTransformerChain:
    arguments:
      $transformers:
        - '@Strix\Ergonode\Transformer\ProductTransformer'
        - '@Strix\Ergonode\Transformer\ProductCategoryTransformer'
        - '@Strix\Ergonode\Transformer\ProductTaxTransformer'
        - '@Strix\Ergonode\Transformer\ProductPriceTransformer'
        - '@Strix\Ergonode\Transformer\ProductDefaultValuesTransformer'
        - '@Strix\Ergonode\Transformer\ProductMediaTransformer'
        - '@Strix\Ergonode\Transformer\ProductCustomFieldTransformer'
        - '@Strix\Ergonode\Transformer\ProductPropertiesTransformer'
